version: '3.8'

services:
  playlistarr:
    image: ghcr.io/eatprilosec/playlistarr:master
    container_name: playlistarr
    restart: unless-stopped
    ports:
      - "8671:8671"
    volumes:
      - ./data:/app/data
