version: '3.8'

services:
  playlistarr:
    image: ghcr.io/eatprilosec/playlistarr:master
    container_name: playlistarr
    restart: unless-stopped
    ports:
      - "8670:8670"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/playlistarr.db
